"""rename address

Revision ID: 960111a1e01f
Revises: b04fc6fb21e4
Create Date: 2024-04-04 11:12:17.686177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960111a1e01f'
down_revision = 'b04fc6fb21e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
